/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as StoreRouteImport } from './routes/store'
import { Route as OrderNumberRouteImport } from './routes/order.$number'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as SchoolIdRouteImport } from './routes/school.$id'
import { Route as ShopDeptRouteImport } from './routes/shop.$dept'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffBakeryRouteImport } from './routes/staff/bakery'
import { Route as StaffCustomersRouteImport } from './routes/staff/customers'
import { Route as StaffDeliveriesRouteImport } from './routes/staff/deliveries'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffOrdersRouteImport } from './routes/staff/orders'
import { Route as StaffPosRouteImport } from './routes/staff/pos'
import { Route as StaffProductsRouteImport } from './routes/staff/products'
import { Route as StaffPromosRouteImport } from './routes/staff/promos'
import { Route as StaffReportsRouteImport } from './routes/staff/reports'
import { Route as StaffSchoolRouteImport } from './routes/staff/school'
import { Route as StaffSettingsRouteImport } from './routes/staff/settings'
import { Route as StaffSuppliersRouteImport } from './routes/staff/suppliers'
import { Route as StaffOrdersIdRouteImport } from './routes/staff/orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderNumberRoute = OrderNumberRouteImport.update({
  id: '/order/$number',
  path: '/order/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolIdRoute = SchoolIdRouteImport.update({
  id: '/school/$id',
  path: '/school/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopDeptRoute = ShopDeptRouteImport.update({
  id: '/shop/$dept',
  path: '/shop/$dept',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffBakeryRoute = StaffBakeryRouteImport.update({
  id: '/bakery',
  path: '/bakery',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffCustomersRoute = StaffCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffDeliveriesRoute = StaffDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffPosRoute = StaffPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffProductsRoute = StaffProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffPromosRoute = StaffPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffSchoolRoute = StaffSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffSuppliersRoute = StaffSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffOrdersIdRoute = StaffOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/staff': typeof StaffRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/offers': typeof OffersRoute
  '/search': typeof SearchRoute
  '/store': typeof StoreRoute
  '/order/$number': typeof OrderNumberRoute
  '/p/$slug': typeof PSlugRoute
  '/school/$id': typeof SchoolIdRoute
  '/shop/$dept': typeof ShopDeptRoute
  '/staff/bakery': typeof StaffBakeryRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/deliveries': typeof StaffDeliveriesRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/orders': typeof StaffOrdersRouteWithChildren
  '/staff/pos': typeof StaffPosRoute
  '/staff/products': typeof StaffProductsRoute
  '/staff/promos': typeof StaffPromosRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/school': typeof StaffSchoolRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/suppliers': typeof StaffSuppliersRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/orders/$id': typeof StaffOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/offers': typeof OffersRoute
  '/search': typeof SearchRoute
  '/store': typeof StoreRoute
  '/order/$number': typeof OrderNumberRoute
  '/p/$slug': typeof PSlugRoute
  '/school/$id': typeof SchoolIdRoute
  '/shop/$dept': typeof ShopDeptRoute
  '/staff/bakery': typeof StaffBakeryRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/deliveries': typeof StaffDeliveriesRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/orders': typeof StaffOrdersRouteWithChildren
  '/staff/pos': typeof StaffPosRoute
  '/staff/products': typeof StaffProductsRoute
  '/staff/promos': typeof StaffPromosRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/school': typeof StaffSchoolRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/suppliers': typeof StaffSuppliersRoute
  '/staff': typeof StaffIndexRoute
  '/staff/orders/$id': typeof StaffOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/staff': typeof StaffRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/offers': typeof OffersRoute
  '/search': typeof SearchRoute
  '/store': typeof StoreRoute
  '/order/$number': typeof OrderNumberRoute
  '/p/$slug': typeof PSlugRoute
  '/school/$id': typeof SchoolIdRoute
  '/shop/$dept': typeof ShopDeptRoute
  '/staff/bakery': typeof StaffBakeryRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/deliveries': typeof StaffDeliveriesRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/orders': typeof StaffOrdersRouteWithChildren
  '/staff/pos': typeof StaffPosRoute
  '/staff/products': typeof StaffProductsRoute
  '/staff/promos': typeof StaffPromosRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/school': typeof StaffSchoolRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/suppliers': typeof StaffSuppliersRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/orders/$id': typeof StaffOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/staff'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/offers'
    | '/search'
    | '/store'
    | '/order/$number'
    | '/p/$slug'
    | '/school/$id'
    | '/shop/$dept'
    | '/staff/bakery'
    | '/staff/customers'
    | '/staff/deliveries'
    | '/staff/login'
    | '/staff/orders'
    | '/staff/pos'
    | '/staff/products'
    | '/staff/promos'
    | '/staff/reports'
    | '/staff/school'
    | '/staff/settings'
    | '/staff/suppliers'
    | '/staff/'
    | '/staff/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/offers'
    | '/search'
    | '/store'
    | '/order/$number'
    | '/p/$slug'
    | '/school/$id'
    | '/shop/$dept'
    | '/staff/bakery'
    | '/staff/customers'
    | '/staff/deliveries'
    | '/staff/login'
    | '/staff/orders'
    | '/staff/pos'
    | '/staff/products'
    | '/staff/promos'
    | '/staff/reports'
    | '/staff/school'
    | '/staff/settings'
    | '/staff/suppliers'
    | '/staff'
    | '/staff/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/staff'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/offers'
    | '/search'
    | '/store'
    | '/order/$number'
    | '/p/$slug'
    | '/school/$id'
    | '/shop/$dept'
    | '/staff/bakery'
    | '/staff/customers'
    | '/staff/deliveries'
    | '/staff/login'
    | '/staff/orders'
    | '/staff/pos'
    | '/staff/products'
    | '/staff/promos'
    | '/staff/reports'
    | '/staff/school'
    | '/staff/settings'
    | '/staff/suppliers'
    | '/staff/'
    | '/staff/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OffersRoute: typeof OffersRoute
  SearchRoute: typeof SearchRoute
  StoreRoute: typeof StoreRoute
  OrderNumberRoute: typeof OrderNumberRoute
  PSlugRoute: typeof PSlugRoute
  SchoolIdRoute: typeof SchoolIdRoute
  ShopDeptRoute: typeof ShopDeptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$number': {
      id: '/order/$number'
      path: '/order/$number'
      fullPath: '/order/$number'
      preLoaderRoute: typeof OrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/$id': {
      id: '/school/$id'
      path: '/school/$id'
      fullPath: '/school/$id'
      preLoaderRoute: typeof SchoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$dept': {
      id: '/shop/$dept'
      path: '/shop/$dept'
      fullPath: '/shop/$dept'
      preLoaderRoute: typeof ShopDeptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/bakery': {
      id: '/staff/bakery'
      path: '/bakery'
      fullPath: '/staff/bakery'
      preLoaderRoute: typeof StaffBakeryRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/customers': {
      id: '/staff/customers'
      path: '/customers'
      fullPath: '/staff/customers'
      preLoaderRoute: typeof StaffCustomersRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/deliveries': {
      id: '/staff/deliveries'
      path: '/deliveries'
      fullPath: '/staff/deliveries'
      preLoaderRoute: typeof StaffDeliveriesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/orders': {
      id: '/staff/orders'
      path: '/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/pos': {
      id: '/staff/pos'
      path: '/pos'
      fullPath: '/staff/pos'
      preLoaderRoute: typeof StaffPosRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/products': {
      id: '/staff/products'
      path: '/products'
      fullPath: '/staff/products'
      preLoaderRoute: typeof StaffProductsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/promos': {
      id: '/staff/promos'
      path: '/promos'
      fullPath: '/staff/promos'
      preLoaderRoute: typeof StaffPromosRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/school': {
      id: '/staff/school'
      path: '/school'
      fullPath: '/staff/school'
      preLoaderRoute: typeof StaffSchoolRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/suppliers': {
      id: '/staff/suppliers'
      path: '/suppliers'
      fullPath: '/staff/suppliers'
      preLoaderRoute: typeof StaffSuppliersRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/orders/$id': {
      id: '/staff/orders/$id'
      path: '/$id'
      fullPath: '/staff/orders/$id'
      preLoaderRoute: typeof StaffOrdersIdRouteImport
      parentRoute: typeof StaffOrdersRoute
    }
  }
}

interface StaffOrdersRouteChildren {
  StaffOrdersIdRoute: typeof StaffOrdersIdRoute
}

const StaffOrdersRouteChildren: StaffOrdersRouteChildren = {
  StaffOrdersIdRoute: StaffOrdersIdRoute,
}

const StaffOrdersRouteWithChildren = StaffOrdersRoute._addFileChildren(
  StaffOrdersRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffBakeryRoute: typeof StaffBakeryRoute
  StaffCustomersRoute: typeof StaffCustomersRoute
  StaffDeliveriesRoute: typeof StaffDeliveriesRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffOrdersRoute: typeof StaffOrdersRouteWithChildren
  StaffPosRoute: typeof StaffPosRoute
  StaffProductsRoute: typeof StaffProductsRoute
  StaffPromosRoute: typeof StaffPromosRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffSchoolRoute: typeof StaffSchoolRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffSuppliersRoute: typeof StaffSuppliersRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffBakeryRoute: StaffBakeryRoute,
  StaffCustomersRoute: StaffCustomersRoute,
  StaffDeliveriesRoute: StaffDeliveriesRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffOrdersRoute: StaffOrdersRouteWithChildren,
  StaffPosRoute: StaffPosRoute,
  StaffProductsRoute: StaffProductsRoute,
  StaffPromosRoute: StaffPromosRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffSchoolRoute: StaffSchoolRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffSuppliersRoute: StaffSuppliersRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OffersRoute: OffersRoute,
  SearchRoute: SearchRoute,
  StoreRoute: StoreRoute,
  OrderNumberRoute: OrderNumberRoute,
  PSlugRoute: PSlugRoute,
  SchoolIdRoute: SchoolIdRoute,
  ShopDeptRoute: ShopDeptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
